#!/usr/bin/env python
"""Thorough review of J-space (workspace) contents across ALL saved readouts.

Reads only JSON (safe while the model is busy). Per prompt: dominant concepts by stage
(early/mid/late reasoning), category tracking (numbers / doubt-meta / self-aware / negation /
task-answer), layer contrast (L14 vs L20 vs L26), and 'silent' concepts (loaded but absent
from the produced text). Cross-prompt summary at the end. Emits a readable report to
results/workspace/JSPACE_REVIEW.md.
"""
import glob, json, os, re
from collections import Counter, defaultdict

WS = "results/workspace"
LP = "20"  # primary workspace layer
CATS = {
    "numbers": {"one","two","three","four","five","six","seven","eight","nine","ten","eleven",
                "twelve","thirteen","fourteen","fifteen","twenty","thirty","forty","fifty","hundred"},
    "doubt/meta": {"maybe","wait","hmm","actually","perhaps","but","however","confused","confusion",
                   "mistake","wrong","doubt","unsure","again","guess","suppose","seems","recheck"},
    "self-aware": {"funny","obvious","obviously","clearly","ridiculous","silly","absurd","stuck",
                   "endless","weird","strange","tedious"},
    "negation/none": {"none","no","not","never","impossible","empty","zero","nothing","cannot"},
}
GARBAGE = re.compile(r"[一-鿿぀-ヿ가-힯]")  # CJK/Kana/Hangul


def stage_of(i, n):
    return "early" if i < n/3 else "mid" if i < 2*n/3 else "late"


def review_file(path, primary=LP):
    d = json.load(open(path))
    pos = sorted((int(k) for k in d["positions"]), key=int)
    plen = d.get("prompt_len", 0)
    reason = [p for p in pos if p >= plen] or pos
    n = len(reason)
    top_by_stage = {"early": Counter(), "mid": Counter(), "late": Counter()}
    cat_hits = defaultdict(list)   # cat -> [(pos, concept, weight)]
    layer_top = {l: Counter() for l in ("14", "20", "26")}
    garbage_frac = {l: 0 for l in ("14", "20", "26")}
    total_cells = {l: 0 for l in ("14", "20", "26")}
    for i, p in enumerate(reason):
        rec = d["positions"][str(p)]["by_layer"]
        st = stage_of(i, n)
        for c, w in rec.get(primary, [])[:6]:
            top_by_stage[st][c.lower()] += 1
        for l in ("14", "20", "26"):
            cs = rec.get(l, [])
            for rank, (c, w) in enumerate(cs):
                total_cells[l] += 1
                if GARBAGE.search(c):
                    garbage_frac[l] += 1
                layer_top[l][c.lower()] += 1
                cl = c.lower()
                for cat, words in CATS.items():
                    if cl in words:
                        cat_hits[cat].append((p, cl, w, l, rank))
    # silent concepts: high-weight concepts at L20 never present in the trace text
    trace = d.get("trace", "").lower()
    silent = Counter()
    for p in reason:
        for c, w in d["positions"][str(p)]["by_layer"].get(primary, [])[:4]:
            cl = c.lower().strip()
            if len(cl) > 3 and cl.isalpha() and cl not in trace and not GARBAGE.search(cl):
                silent[cl] += w
    return {
        "id": d.get("id", os.path.basename(path)), "category": d.get("category", ""),
        "gold": d.get("gold"), "answer": d.get("answer"), "correct": d.get("correct"),
        "n_reason": n, "n_prompt": plen,
        "top_by_stage": {s: top_by_stage[s].most_common(8) for s in top_by_stage},
        "cat_summary": {cat: {"count": len(cat_hits.get(cat, [])),
                              "best": sorted(cat_hits.get(cat, []), key=lambda x: x[4])[:3]}
                        for cat in CATS},
        "garbage": {l: round(garbage_frac[l]/max(total_cells[l], 1), 2) for l in garbage_frac},
        "silent_top": silent.most_common(8),
    }


def w(f, s=""):
    f.write(s + "\n")


def main():
    out = open(f"{WS}/JSPACE_REVIEW.md", "w")
    w(out, "# J-space contents — thorough review across all prompts\n")
    w(out, f"Primary layer L{LP}. Generated by `mvp/jspace_review.py` over saved workspace readouts.\n")

    groups = [
        ("REASONING / SPIRAL (6q)", sorted(glob.glob(f"{WS}/6q/*_masked.json"))),
        ("DECEPTION", sorted(glob.glob(f"{WS}/deception/*.json"))),
        ("CONNECTION (think vs nothink)", sorted(glob.glob(f"{WS}/connect/*.json"))),
    ]
    allrev = []
    for gname, files in groups:
        files = [f for f in files if "status" not in f and "_n45" not in f]
        if not files:
            continue
        w(out, f"\n## {gname}\n")
        for path in files:
            try:
                r = review_file(path)
            except Exception as e:
                w(out, f"### {os.path.basename(path)} — SKIP ({e})"); continue
            allrev.append((gname, r))
            w(out, f"### {r['id']}  ·  {r['category']}")
            w(out, f"- gold `{r['gold']}` answer `{str(r['answer'])[:40]}` correct={r['correct']} · "
                   f"{r['n_prompt']} prompt + {r['n_reason']} reasoning tokens")
            w(out, f"- garbage fraction by layer: L14={r['garbage']['14']} L20={r['garbage']['20']} L26={r['garbage']['26']}")
            for st in ("early", "mid", "late"):
                top = ", ".join(f"{c}×{n}" for c, n in r["top_by_stage"][st][:6])
                w(out, f"- **{st} reasoning** top L{LP}: {top}")
            for cat, cs in r["cat_summary"].items():
                if cs["count"]:
                    ex = "; ".join(f"{c}@p{p}(L{l},r{rk},w{round(wt,2)})" for p, c, wt, l, rk in cs["best"])
                    w(out, f"- {cat}: {cs['count']} hits — {ex}")
            if r["silent_top"]:
                w(out, f"- silent (loaded L{LP}, absent from text): " +
                       ", ".join(f"{c}({round(wt,2)})" for c, wt in r["silent_top"][:6]))
            w(out)

    # cross-prompt patterns
    w(out, "\n## CROSS-PROMPT PATTERNS\n")
    w(out, "### garbage fraction (early-layer noise) by group")
    for gname in {g for g, _ in allrev}:
        gs = [r for g, r in allrev if g == gname]
        for l in ("14", "20", "26"):
            vals = [r["garbage"][l] for r in gs]
            w(out, f"- {gname} L{l}: mean garbage {round(sum(vals)/max(len(vals),1),2)}")
    w(out, "\n### doubt/meta load ranking (mid+late, count of hits)")
    ranked = sorted(((r["id"], r["cat_summary"]["doubt/meta"]["count"]) for g, r in allrev),
                    key=lambda x: -x[1])
    for pid, c in ranked[:15]:
        w(out, f"- {pid}: {c}")
    w(out, "\n### self-aware concept appearances (funny/obvious/…)")
    for g, r in allrev:
        c = r["cat_summary"]["self-aware"]["count"]
        if c:
            w(out, f"- {r['id']}: {c}")
    out.close()
    print(f"wrote {WS}/JSPACE_REVIEW.md  ({len(allrev)} prompts reviewed)")
    # also print the headline cross-prompt bits to stdout
    print("\n=== doubt/meta load (top 8) ===")
    for pid, c in ranked[:8]:
        print(f"  {pid:26} {c}")


if __name__ == "__main__":
    main()
